import { inter } from '@/app/ui/fonts';
import "./globals.css";

import { ApolloProvider } from "@apollo/client";

import Header from "./ui/header";
import { ApolloWrapper } from "./AppoloWrapper";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
        <ApolloWrapper>
          <Header />

          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}
